---
title: "emotion + puberty for flux 2023"
author: "cfm"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    df_print: paged
    highlight: tango
    theme: united
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  pdf_document:
    toc: yes
---

### Setting up markdown {.tabset}

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)

options(scipen=999)
```

### loading required packages

```{r Load Required Packages, message=FALSE, warning=FALSE, include=FALSE}

# load packages

library(pacman)
pacman::p_load(dplyr, ggseg, ggplot2, tidyr, lubridate, psych, lme4, lmerTest, data.table, install = TRUE)

```

# Setting root path 

```{r root path}

root = "/Users/clare/Dropbox (University of Oregon)/mine/projects/flux_EmotionPuberty/"

```

# Loading in data 

```{r load in data}

# hp_timing <- read.csv(paste0(root, "data/hormonal_puberty_age_gap.csv"))
# 
# p_timing <- read.csv(paste0(root, "data/physical_puberty_age_gap.csv"))

pds <- read.csv(paste0(root, "data/ph_y_pds.csv"))

hormones <- read.csv(paste0(root, "data/ph_y_sal_horm.csv"))

cbcl <- read.csv(paste0(root, "data/mh_p_cbcl.csv"))

demo <- read.csv(paste0(root, "data/abcd_p_demo.csv")) %>% 
    rename("id" = "src_subject_id",
           "wave" = "eventname",
           "grade" = "demo_ed_v2",
           "gender" = "demo_gender_id_v2",
           "white" = "demo_prnt_race_a_v2___10",
           "black" = "demo_prnt_race_a_v2___11",
           "aina" = "demo_prnt_race_a_v2___12",
           "an" = "demo_prnt_race_a_v2___13",
           "nh" = "demo_prnt_race_a_v2___14",
           "guam" = "demo_prnt_race_a_v2___15",
           "samoan" = "demo_prnt_race_a_v2___16",
           "pin" = "demo_prnt_race_a_v2___17",
           "indian" = "demo_prnt_race_a_v2___18",
           "chinese" = "demo_prnt_race_a_v2___19",
           "filipino" = "demo_prnt_race_a_v2___20",
           "japanese" = "demo_prnt_race_a_v2___21",
           "korean" = "demo_prnt_race_a_v2___22",
           "vietnamese" = "demo_prnt_race_a_v2___23",
           "asian_other" = "demo_prnt_race_a_v2___24",
           "other" = "demo_prnt_race_a_v2___25",
           "refuse_race" = "demo_prnt_race_a_v2___77",
           "dont_know_race" = "demo_prnt_race_a_v2___99",
           "ethn" = "demo_ethn_v2",
           "ethn_specified" = "demo_ethn2_v2",
           "income" = "demo_prnt_income_v2_l") %>% 
  select(id, wave, white, black, aina, an, nh, guam, samoan, pin, indian, chinese, filipino, japanese, vietnamese, asian_other, other, refuse_race, dont_know_race, ethn, ethn_specified, income)

tracking <- read.csv(paste0(root, "data/abcd_y_lt.csv"))

anthro <- read.csv(paste0(root, "data/ph_y_anthro.csv"))

brain_aseg <- read.csv(paste0(root, "data/brain/mri_y_tfmr_nback_emovntf_aseg.csv")) %>% 
  rename("id" = "src_subject_id",
         "wave" = "eventname",
         "l_amyg" = "tfmri_nback_all_194",
         "r_amyg" = "tfmri_nback_all_208",
         "l_caudate" = "tfmri_nback_all_187",
         "r_caudate" = "tfmri_nback_all_204") %>% 
  filter(!is.na(l_amyg),
         !is.na(r_amyg),
         !is.na(l_caudate),
         !is.na(r_caudate)) %>% 
  select(id, wave, l_amyg, r_amyg, l_caudate, r_caudate)


```

# Cleaning puberty data 

```{r cleaning puberty data}

## remove unecessary columns + recoding hormone sex variable to match scheme of PDS + renaming columns to match puberty-age-gap pipeline 

 pds <- pds %>% 
  select(src_subject_id, eventname, pds_sex_y, pds_ht2_y, pds_bdyhair_y, pds_skin2_y, pds_f4_2_y, pds_f5_y, pds_m4_y, pds_m5_y, pds_y_ss_female_category, pds_y_ss_male_category) %>% 
  rename("sex" = "pds_sex_y",
         "id" = "src_subject_id",
         "wave" = "eventname", 
         "growth_spurt" = "pds_ht2_y",
         "body_hair" = "pds_bdyhair_y", 
         "skin_change" = "pds_skin2_y",
         "breast_develop" = "pds_f4_2_y",
         "menarche" = "pds_f5_y",
         "voice_deep" = "pds_m4_y",
         "face_hair" = "pds_m5_y",
         "pds_f" = "pds_y_ss_female_category",
         "pds_m" = "pds_y_ss_male_category") %>% 
  group_by(id) %>%
  mutate(sex = ifelse(is.na(sex), first(na.omit(sex)), sex)) 

hormones <- hormones %>% 
  select(src_subject_id, eventname, hormone_sal_sex, hormone_scr_dhea_mean, hormone_scr_ert_mean, hormone_sal_caff_y, hormone_sal_active, hormone_sal_start_y, hormone_sal_end_y, hormone_sal_freezer_y) %>% 
  mutate(hormone_sal_sex = ifelse(hormone_sal_sex == 1, 2,
                                  ifelse(hormone_sal_sex == 2, 1,
                                         hormone_sal_sex))) %>% 
  rename("id" = "src_subject_id",
         "wave" = "eventname",
         "sex" = "hormone_sal_sex",
         "dhea" = "hormone_scr_dhea_mean", 
         "tst" = "hormone_scr_ert_mean",
         "caffeine" = "hormone_sal_caff_y",
         "active" = "hormone_sal_active",
         "start_time" = "hormone_sal_start_y",
         "end_time" = "hormone_sal_end_y",
         "freezer" = "hormone_sal_freezer_y") %>% 
  group_by(id) %>%
  mutate(sex = ifelse(is.na(sex), first(na.omit(sex)), sex)) 

calculate_time_difference <- function(time1, time2) {
  # Convert times with colons to POSIXct objects
  time1_posix <- as.POSIXct(time1, format = "%H:%M")
  time2_posix <- as.POSIXct(time2, format = "%H:%M")
  
  # Calculate the difference in minutes
  time_difference <- as.numeric(difftime(time2_posix, time1_posix, units = "mins"))
  
  return(time_difference)
}

hormones$sample_collection_time <- calculate_time_difference(hormones$start_time, hormones$end_time)

hormones$time_to_freezer <- calculate_time_difference(hormones$end_time, hormones$freezer)

calculate_minutes_since_midnight <- function(time) {
  # Convert time with colons to POSIXct object
  time_posix <- as.POSIXct(time, format = "%H:%M")
  
  # Calculate the time difference in minutes
  minutes_since_midnight <- as.numeric(difftime(time_posix, trunc(time_posix, "day"), units = "mins"))
  
  return(minutes_since_midnight)
}

hormones$midnight_to_start <- calculate_minutes_since_midnight(hormones$start_time)

tracking$interview_date <- as.Date(tracking$interview_date, format = "%m/%d/%Y")

covid_cutoff <- as.Date("03/01/2020", format = "%m/%d/%Y")

tracking <- tracking %>% 
  mutate(covid_date = ifelse(interview_date >= covid_cutoff, 1, 0))


tracking <- tracking %>% 
  select(src_subject_id, eventname, site_id_l, rel_family_id, interview_age, covid_date) %>% 
  rename("id" = "src_subject_id",
         "wave" = "eventname",
         "site_id" = "site_id_l",
         "family_id" = "rel_family_id",
         "age" = "interview_age") %>% 
  group_by(id) %>%
  mutate(site_id = ifelse(is.na(site_id), first(na.omit(site_id)), site_id)) %>% 
  mutate(family_id = ifelse(is.na(family_id), first(na.omit(family_id)), family_id)) %>% 
  filter(!is.na(site_id),
         !is.na(family_id))

anthro$BMI <- (anthro$anthroweightcalc / (anthro$anthroheightcalc)^2) * 703

anthro <-  anthro %>% 
  select(src_subject_id, eventname, BMI) %>% 
  rename("id" = "src_subject_id",
         "wave" = "eventname") %>% 
  filter(!is.na(BMI))

## exclude based on: no hormones and/or PDS, no family and/or site, no sex match btw pds and hormones 

## filtering out IDs and timepoints of IDs without both hormones and PDS 

have_both_ids <- intersect(paste(pds$id, pds$wave, sep = "_"),
                           paste(hormones$id, hormones$wave, sep = "_"))

pds_cleaned <- pds %>% 
  filter(paste(id, wave, sep = "_") %in% have_both_ids)

hormones_cleaned <- hormones %>% 
  filter(paste(id, wave, sep = "_") %in% have_both_ids)

pds_cleaned <- left_join(pds_cleaned, left_join(anthro, tracking), by = c("id", "wave"))

puberty <- left_join(pds_cleaned, hormones_cleaned, by = c("id", "wave")) %>% 
  filter(!is.na(dhea),
         !is.na(tst),
         sex.x == sex.y)

puberty$sample_collection_time <- abs(puberty$sample_collection_time)

# exploring how many rows put 999 or 777 for PDS 

count <- sum(rowSums(puberty == 999 | puberty == 777, na.rm = TRUE) > 0, na.rm = TRUE)

# 8163 rows contain a 999 or 777

# creating df for each sex, removing NAs and any rows with 999 or 777 

puberty_male <- puberty[which(puberty$sex.x == 1),]
puberty_female <- puberty[which(puberty$sex.x == 2),]

puberty_female <- puberty_female %>% 
  select(-voice_deep, -face_hair) %>% 
  filter(!is.na(growth_spurt),
         !is.na(body_hair),
         !is.na(skin_change),
         !is.na(breast_develop),
         !is.na(menarche),
         !is.na(sample_collection_time),
         !is.na(caffeine),
         !is.na(active),
         !is.na(midnight_to_start),
         !is.na(site_id),
         !is.na(time_to_freezer),
         !is.na(covid_date),
         !is.na(age)) %>% 
  filter(!growth_spurt == 999,
         !growth_spurt == 777,
         !body_hair == 999,
         !body_hair == 777,
         !skin_change == 999,
         !skin_change == 777,
         !breast_develop == 999,
         !breast_develop == 777,
         !menarche == 999,
         !menarche == 777)

puberty_male <- puberty_male %>% 
  select(-breast_develop, -menarche) %>% 
  filter(!is.na(growth_spurt),
         !is.na(body_hair),
         !is.na(skin_change),
         !is.na(face_hair),
         !is.na(voice_deep),
         !is.na(sample_collection_time),
         !is.na(caffeine),
         !is.na(active),
         !is.na(midnight_to_start),
         !is.na(site_id),
         !is.na(time_to_freezer),
         !is.na(covid_date),
         !is.na(age)) %>% 
  filter(!growth_spurt == 999,
         !growth_spurt == 777,
         !body_hair == 999,
         !body_hair == 777,
         !skin_change == 999,
         !skin_change == 777,
         !face_hair == 999,
         !face_hair == 777,
         !voice_deep == 999,
         !voice_deep == 777)


# cleaning environment 

rm(hormones, hormones_cleaned, pds, pds_cleaned, tracking, count, have_both_ids, anthro)

```

# Removing confound effects for hormone data 

```{r remove confounding effects for hormone data}

## removing outliers 

summary(puberty_female)
boxplot(puberty_female$sample_collection_time)

puberty_female <- puberty_female %>% 
  filter(sample_collection_time < 200)

na_counts <- colSums(is.na(puberty_female))
print(na_counts)

summary(puberty_male)
boxplot(puberty_male$sample_collection_time)

puberty_male <- puberty_male %>% 
  filter(sample_collection_time < 200)

## transform hormone data to normal and standardize all other variables 

library("moments")

## to normalize (1/x)

skewness(puberty_female$dhea)
skewness(puberty_female$tst)
skewness(puberty_male$dhea)
skewness(puberty_male$tst)

puberty_female$dhea_norm <- log10(puberty_female$dhea)
skewness(puberty_female$dhea_norm)

puberty_female$tst_norm <- log10(puberty_female$tst)
skewness(puberty_female$tst_norm)

puberty_male$dhea_norm <- log10(puberty_male$dhea)
skewness(puberty_male$dhea_norm)

puberty_male$tst_norm <- log10(puberty_male$tst)
skewness(puberty_male$tst_norm)

hist(puberty_female$dhea_norm)
hist(puberty_female$tst_norm)
hist(puberty_male$dhea_norm)
hist(puberty_male$tst_norm)

## removing confounding effects 

model_f_dhea <- lmer(dhea_norm ~ caffeine +  sample_collection_time  + midnight_to_start + time_to_freezer + covid_date + (1 | site_id) + (1 | id), data = puberty_female)

model_f_tst <- lmer(tst_norm ~ caffeine +  sample_collection_time + midnight_to_start +  time_to_freezer + covid_date + (1 | site_id) + (1 | id), data = puberty_female)

model_m_dhea <- lmer(dhea_norm ~ caffeine + sample_collection_time  + midnight_to_start + time_to_freezer + covid_date + (1 | site_id) + (1 | id), data = puberty_male)

model_m_tst <- lmer(tst_norm ~ caffeine + sample_collection_time + midnight_to_start + time_to_freezer + covid_date + (1 | site_id) + (1 | id), data = puberty_male)

## adding residuals to dataframes 

puberty_female$dhea_unconfounded <- residuals(model_f_dhea)
puberty_female$tst_unconfounded <- residuals(model_f_tst)
puberty_male$dhea_unconfounded <- residuals(model_m_dhea)
puberty_male$tst_unconfounded <- residuals(model_m_tst)

puberty_female$"id-wave" <- paste(puberty_female$id, puberty_female$wave, sep = "-")
puberty_male$"id-wave" <- paste(puberty_male$id, puberty_male$wave, sep = "-")

puberty_female <- puberty_female %>% 
  rename("pds" = "pds_f",
         "sex" = "sex.x") %>% 
  select(-pds_m, -sex.y, -caffeine, -active, -start_time, -end_time, -freezer, -sample_collection_time, -midnight_to_start, -covid_date, -time_to_freezer)

puberty_male <- puberty_male %>% 
  rename("pds" = "pds_m",
         "sex" = "sex.x") %>% 
  select(-pds_f, -sex.y, -caffeine, -active, -start_time, -end_time, -freezer, -sample_collection_time, -midnight_to_start, -covid_date, -time_to_freezer)

write.csv(puberty_female, file = "data/whole_abcd_puberty_female.csv")
write.csv(puberty_male, file = "data/whole_abcd_puberty_male.csv")

scaled_puberty_female <- puberty_female
scaled_puberty_female[,c("age", "dhea_unconfounded", "tst_unconfounded", "growth_spurt", "skin_change", "body_hair", "breast_develop", "menarche")] <- scale(scaled_puberty_female[,c("age", "dhea_unconfounded", "tst_unconfounded", "growth_spurt", "skin_change", "body_hair", "breast_develop", "menarche")])

scaled_puberty_male <- puberty_male
scaled_puberty_male[,c("age", "dhea_unconfounded", "tst_unconfounded", "growth_spurt", "skin_change", "body_hair", "breast_develop", "menarche")] <- scale(scaled_puberty_male[,c("age", "dhea_unconfounded", "tst_unconfounded", "growth_spurt", "skin_change", "body_hair", "voice_deep", "face_hair")])

```

# Creating typically developing dataframe fro puberty-age-gap 
```{r creating TD dataframe for puberty-age-gap}

# typically developing pxs --> anyone who scored less than 60 on the following subscales: affective problems, anxiety problems, somatic problems, ADHD, oppositional defiant problems, conduct problems 

atypical <- cbcl %>% 
  filter(!cbcl_scr_dsm5_conduct_t > 60, 
         !cbcl_scr_dsm5_opposit_t > 60, 
         !cbcl_scr_dsm5_adhd_t > 60,  	
         !cbcl_scr_dsm5_somaticpr_t > 60, 
         !cbcl_scr_dsm5_anxdisord_t > 60, 
         !cbcl_scr_dsm5_depress_t > 60) %>% 
  rename("id" = "src_subject_id",
         "wave" = "eventname")

typical_female <- anti_join(scaled_puberty_female, atypical, by = c("id", "wave"))
typical_male <- anti_join(scaled_puberty_male, atypical, by = c("id", "wave"))

write.csv(typical_female, file = paste0(root, "data/typical_female_all.csv"))

write.csv(typical_male, file = paste0(root, "data/typical_male_all.csv"))

atypical_female <- anti_join(scaled_puberty_female, typical_female, by = c("id", "wave"))
atypical_male <- anti_join(scaled_puberty_male, typical_male, by = c("id", "wave"))

write.csv(atypical_female, file = paste0(root, "data/atypical_female_all.csv"))
write.csv(atypical_male, file = paste0(root, "data/atypical_male_all.csv"))

## creating three separate subsets of typically developing folks with one time point of each id randomly and making sure there are no duplicate family IDs
# Determine the number of subsets
num_subsets <- 5

# Create a new column to indicate subset membership
typical_female$subset <- sample(1:num_subsets, size = nrow(typical_female), replace = TRUE)

# Function to filter unique IDs and family IDs within a subset
filter_unique_ids <- function(subset) {
  subset_ids <- unique(c(subset$id, subset$family_id))
  subset %>% filter(id %in% subset_ids, family_id %in% subset_ids)
}

# Create filtered subsets with unique IDs and family IDs
subset1_female <- filter_unique_ids(typical_female[typical_female$subset == 1, ])
subset2_female <- filter_unique_ids(typical_female[typical_female$subset == 2, ])
subset3_female <- filter_unique_ids(typical_female[typical_female$subset == 3, ])
subset4_female <- filter_unique_ids(typical_female[typical_female$subset == 4, ])
subset5_female <- filter_unique_ids(typical_female[typical_female$subset == 5, ])

write.csv(subset1_female, file = paste0(root, "data/typical_female_1.csv"))
write.csv(subset2_female, file = paste0(root, "data/typical_female_2.csv"))
write.csv(subset3_female, file = paste0(root, "data/typical_female_3.csv"))
write.csv(subset4_female, file = paste0(root, "data/typical_female_4.csv"))
write.csv(subset5_female, file = paste0(root, "data/typical_female_5.csv"))

## in males

num_subsets <- 5

# Create a new column to indicate subset membership
typical_male$subset <- sample(1:num_subsets, size = nrow(typical_male), replace = TRUE)

# Function to filter unique IDs and family IDs within a subset
filter_unique_ids <- function(subset) {
  subset_ids <- unique(c(subset$id, subset$family_id))
  subset %>% filter(id %in% subset_ids, family_id %in% subset_ids)
}

# Create filtered subsets with unique IDs and family IDs
subset1_male <- filter_unique_ids(typical_male[typical_male$subset == 1, ])
subset2_male <- filter_unique_ids(typical_male[typical_male$subset == 2, ])
subset3_male <- filter_unique_ids(typical_male[typical_male$subset == 3, ])
subset4_male <- filter_unique_ids(typical_male[typical_male$subset == 4, ])
subset5_male <- filter_unique_ids(typical_male[typical_male$subset == 5, ])

write.csv(subset1_male, file = paste0(root, "data/typical_male_1.csv"))
write.csv(subset2_male, file = paste0(root, "data/typical_male_2.csv"))
write.csv(subset3_male, file = paste0(root, "data/typical_male_3.csv"))
write.csv(subset4_male, file = paste0(root, "data/typical_male_4.csv"))
write.csv(subset5_male, file = paste0(root, "data/typical_male_5.csv"))

```

```{r cleaning cbcl}

cbcl <- cbcl %>% 
  rename("id" = "src_subject_id",
         "wave" = "eventname")

cbcl_female <- left_join(female, cbcl, by = c("id", "wave"))
cbcl_male <- left_join(male, cbcl, by = c("id", "wave"))

cbcl_female <- cbcl_female %>% 
  select(id, wave, cbcl_scr_syn_internal_t, cbcl_scr_dsm5_depress_t, cbcl_scr_dsm5_anxdisord_t, cbcl_scr_syn_social_t, cbcl_scr_07_stress_t, cbcl_scr_syn_totprob_t)


cbcl_male <- cbcl_male %>% 
  select(id, wave, cbcl_scr_syn_internal_t, cbcl_scr_dsm5_depress_t, cbcl_scr_dsm5_anxdisord_t, cbcl_scr_syn_social_t, cbcl_scr_07_stress_t, cbcl_scr_syn_totprob_t)


```


```{r brain data}


whole_female <- left_join(puberty_female, brain_aseg, by = c("id", "wave")) %>% 
  filter(!is.na(l_amyg))

whole_male <- left_join(puberty_male, brain_aseg, by = c("id", "wave")) %>% 
  filter(!is.na(l_amyg))


```

```{r loading in clean whole docs to generate descriptives}


whole_female <- read.csv(paste0(root, "data/whole_abcd_puberty_female.csv"))
whole_male <- read.csv(paste0(root, "data/whole_abcd_puberty_male.csv"))

whole_female <- left_join(whole_female, brain_aseg, by = c("id", "wave")) %>% 
  filter(!is.na(l_amyg))

whole_male <- left_join(whole_male, brain_aseg, by = c("id", "wave")) %>% 
  filter(!is.na(l_amyg))

## clean demo data 

demo <- demo %>% 
  filter(!is.na(white))

## sex from puberty data, age, race

demo_ids <- left_join(whole_female, demo, by = c("id", "wave")) %>% 
  filter(!is.na(white),
         !is.na(black),
         !is.na(aina),
         !is.na(an),
         !is.na(nh),
         !is.na(guam),
         !is.na(samoan), 
         !is.na(pin),
         !is.na(indian),
         !is.na(chinese),
         !is.na(filipino),
         !is.na(japanese),
         !is.na(vietnamese),
         !is.na(asian_other),
         !is.na(other),
         !is.na(refuse_race),
         !is.na(dont_know_race),
         !is.na(ethn))

race_columns <- c(26:43)

count_race <- colSums(demo_ids[race_columns] == 1)

print(count_race)

## how many people report more than one race 

num_rows_mult_race <- rowSums(demo_ids[race_columns] == 1) > 1

print(num_rows_mult_race)

multi_race <- demo_ids[num_rows_mult_race, ]

multi_race <- multi_race[,c(2, 26:43)]

multi_race <- multi_race %>% 
  pivot_longer(cols = 2:19, names_to = "race", values_to = "yes_no") %>% 
  filter(yes_no == 1)

multi_race_together <- multi_race %>% 
  group_by(id) %>% 
  summarize(race_joined = paste(race, collapse = "_"))

multi_race_together$yes_no <- 1

multi_race_together <- multi_race_together %>% 
  pivot_wider(names_from = race_joined, values_from = yes_no) %>% 
  mutate(across(everything(), ~ ifelse(is.na(.), 0, .)))

single_race <- demo_ids[!num_rows_mult_race, ]

single_race <- single_race[,c(2,26:43)]

race <- full_join(multi_race_together, single_race) %>% 
  mutate(across(everything(), ~ ifelse(is.na(.), 0, .)))

race_columns <- c(2:63)

brain_counts <- colSums(race[race_columns] == 1)

print(brain_counts)

write.csv(brain_counts, file = paste0(root, "output/brain_sample_race_count_female.csv"))


### whole sample counts 

whole_female <- read.csv(paste0(root, "data/whole_abcd_puberty_female.csv"))
whole_male <- read.csv(paste0(root, "data/whole_abcd_puberty_male.csv"))

## sex from puberty data, age, race

demo_ids <- left_join(whole_female, demo, by = c("id", "wave")) %>% 
  filter(!is.na(white),
         !is.na(black),
         !is.na(aina),
         !is.na(an),
         !is.na(nh),
         !is.na(guam),
         !is.na(samoan), 
         !is.na(pin),
         !is.na(indian),
         !is.na(chinese),
         !is.na(filipino),
         !is.na(japanese),
         !is.na(vietnamese),
         !is.na(asian_other),
         !is.na(other),
         !is.na(refuse_race),
         !is.na(dont_know_race),
         !is.na(ethn))

race_columns <- c(22:39)

count_race <- colSums(demo_ids[race_columns] == 1)

print(count_race)

## how many people report more than one race 

num_rows_mult_race <- rowSums(demo_ids[race_columns] == 1) > 1

print(num_rows_mult_race)

multi_race <- demo_ids[num_rows_mult_race, ]

multi_race <- multi_race[,c(2, 22:39)]

multi_race <- multi_race %>% 
  pivot_longer(cols = 2:19, names_to = "race", values_to = "yes_no") %>% 
  filter(yes_no == 1)

multi_race_together <- multi_race %>% 
  group_by(id) %>% 
  summarize(race_joined = paste(race, collapse = "_"))

multi_race_together$yes_no <- 1

multi_race_together <- multi_race_together %>% 
  pivot_wider(names_from = race_joined, values_from = yes_no) %>% 
  mutate(across(everything(), ~ ifelse(is.na(.), 0, .)))

single_race <- demo_ids[!num_rows_mult_race, ]

single_race <- single_race[,c(2,22:39)]

race <- full_join(multi_race_together, single_race) %>% 
  mutate(across(everything(), ~ ifelse(is.na(.), 0, .)))

race_columns <- c(2:65)

whole_counts <- colSums(race[race_columns] == 1)

print(whole_counts)

write.csv(whole_counts, file = paste0(root, "output/whole_sample_race_count_female.csv"))

```

```{r study design}

whole <- full_join(whole_female, whole_male)

tracking <- tracking %>% 
  select(id, wave, age)

whole <- left_join(whole, tracking, by = c("id", "wave"))

whole <- whole %>% 
  mutate(wave = ifelse(wave == "baseline_year_1_arm_1", "1",
                       ifelse(wave == "2_year_follow_up_y_arm_1", "2",
                              ifelse(wave == "4_year_follow_up_y_arm_1", "3",
                                     wave))))


whole$age_years <- whole$age.y / 12

study_design <- whole[order(whole$wave, whole$age_years, whole$id),]

## creating levels using ordered doc

whole <- study_design %>%
  mutate(Rank_nr=as.numeric(factor(id,levels=unique(id))))

## creating visualization

study_design_plot<- ggplot(whole,
                          aes(x=age_years,
                              y=Rank_nr,
                              group=id,
                              col=wave,
                              shape=wave)) +
  geom_point(alpha=1, position = position_jitter(height = 3)) +
  geom_line(alpha=.4) +
  expand_limits(y = c(0,10000)) +
  theme(axis.text.y = element_blank()) +
  scale_color_manual(name= "Wave",
                     labels = c("Baseline", "2-year F/U", "4-year F/U"),
                     values = c("#5445b1", "#749dae", "#5c1a33"))  +
  scale_shape_manual(name= "Wave",
              labels= c("Baseline", "2-year F/U", "4-year F/U"),
              values = c(0, 1, 2))+
  ylab("") +
  xlab("Age (months)")+
  scale_y_discrete(breaks=NULL) +
  theme_minimal()

## viewing plot

print(study_design_plot)

## saving png of plot

ggsave(filename=paste0(root_path,"output/tag_study_design_w_shapes.png"),
       plot=tag_study_design_plot, width=6, height=5, units='in', dpi=300)





```
```{r troubleshooting hormone data}

## linear vs growth curve models  

## DHEA for females 

## initial visualizations suggest growth curve modeling fits the data best for DHEA female

mylinearmodel <- lmer(dhea ~ age + (1 | id), data = puberty_female, REML = FALSE)
myexponentialmodel <- lmer(log(dhea) ~ age + (1 | id), data = puberty_female, REML = FALSE)

## comparing R squared 

conditional_r2_lin <- r.squaredGLMM(myexponentialmodel, type = "conditional")
conditional_r2_exp <- r.squaredGLMM(mylinearmodel, type = "conditional")

## DHEA for males 

mylinearmodel <- lmer(dhea ~ age + (1 | id), data = puberty_male, REML = FALSE)
myexponentialmodel <- lmer(log(dhea) ~ age + (1 | id), data = puberty_male, REML = FALSE)

## comparing R squared 

conditional_r2_lin <- r.squaredGLMM(myexponentialmodel, type = "conditional")
conditional_r2_exp <- r.squaredGLMM(mylinearmodel, type = "conditional")


## tst for females 

mylinearmodel <- lmer(tst ~ age + (1 | id), data = puberty_female, REML = FALSE)
myexponentialmodel <- lmer(log(tst) ~ age + (1 | id), data = puberty_female, REML = FALSE)

## comparing R squared 

conditional_r2_lin <- r.squaredGLMM(myexponentialmodel, type = "conditional")
conditional_r2_exp <- r.squaredGLMM(mylinearmodel, type = "conditional")

## tst for males 

mylinearmodel <- lmer(tst ~ age + (1 | id), data = puberty_male, REML = FALSE)
myexponentialmodel <- lmer(log(tst) ~ age + (1 | id), data = puberty_male, REML = FALSE)

## comparing R squared 

conditional_r2_lin <- r.squaredGLMM(myexponentialmodel, type = "conditional")
conditional_r2_exp <- r.squaredGLMM(mylinearmodel, type = "conditional")


# Calculate linear line
trend_model <- lm(dhea ~ age, data = puberty_female)
trend_intercept <- coef(trend_model)[1]
trend_slope <- coef(trend_model)[2]

# Define the exponential growth function
exponential_growth <- function(x, a, b) {
  a * exp(b * x) 
}

# Fit the model using nls
fit <- nls(dhea ~ exponential_growth(age, a, b),
           data = puberty_female,
           start = c(a = 1.662, b = 0.019))

# Generate predicted values using the fitted model
predicted_values <- data.frame(age = puberty_female$age,
                                dhea = predict(fit))

# Plot longitudinal data with exponential growth curve and overall trend line using ggplot2
ggplot(puberty_female, aes(x = age, y = dhea, color = factor(wave))) +
  geom_line(aes(group = id)) +
  geom_point(aes(group = id)) +
  geom_jitter(aes(group = id)) +
  geom_line(data = predicted_values, aes(x = age, y = dhea), color = "black", linetype = "dashed") +
  geom_abline(intercept = trend_intercept, slope = trend_slope, color = "red", linetype = "dotted") +
  labs(x = "age (in months)", y = "dhea") +
  theme_minimal()



```

